### ISSUE TITLE
UPGRADE: provide common base class

### ISSUE THREAD

**Issue by belaban** [jgroups-extras/RollingUpgrades#14]
To reduce the copy&paste waste in the UPGRADE protocols for each JGroups version, create a common base class which has common attributes etc, and have each UPGRADE protocol extend it. This common base class cannot contain any JGroups elements, as this would tie it to a specific JGroups version.

**Comment by pruivo** [comment]
What are your thoughts about this?

I'm not sure if we can do anything about it because, if we create the common class, it would have to use the JGroups annotation (`MBean`, `Property`, `ManagedAttribute`, etc) and it would have to extend `org.jgroups.stack.Protocol`

**Comment by belaban** [comment]
Right, but `Protocol` and `@MBean` is available in all versions. I created a prototype that I'd like to discuss with you (the mvn expert! :-)). It defines `UpgradeBase` in a `base` module, using JGroups 3.6.20. JGroups 5 then defines UPGRADE2 which extends it; no problem....

**Comment by belaban** [comment]
Take a look: https://github.com/jgroups-extras/RollingUpgrades/tree/ru-14. Let's discuss Monday, or after the next meeting if you have time...

**Comment by belaban** [comment]
Created common `base` module (importinmg JGroups 4.x) with `UpgradeBase`; `UPGRADE` in 4 and 5 extend it, 3 is not supported.

**Comment by belaban** [comment]
Closing for now, to fix the other issues, might re-open in the future
