### ISSUE TITLE
Better maven module name

### ISSUE THREAD

**Issue by pruivo** [jgroups-extras/RollingUpgrades#15]
The current project builds the following jars:
```
common-1.1.1.Final-SNAPSHOT.jar
jgroups-4-1.1.1.Final-SNAPSHOT.jar
```
The names above are confusing and don't tell me anything useful and they even look like I have 2 JGroups versions in my `lib/` folder:
```
jgroups-4-1.1.1.Final-SNAPSHOT.jar
jgroups-4.2.17.Final.jar
```

I'm proposing changing the modules names
* common -> jgroups-upgrade-common
* jgroups-X -> jgroupsX-upgrade
* upgrade-server -> jgroups-upgrade-server

Let me know what you think.

**Comment by belaban** [comment]
Sounds good! PR?
