### ISSUE TITLE
Unable to configure "rpcs" for JGroups 5 upgrade protocol

### ISSUE THREAD

**Issue by pruivo** [jgroups-extras/RollingUpgrades#17]
When configuring `UPGRADE` as follow
```xml
<upgrade.UPGRADE active="false" server_address="127.0.0.1" server_port="50051" rpcs="true"/>
```

I got the following exception:

```
2021-11-25 13:40:09,027 ERROR (jgroups-9,site2-s2) [org.jgroups.protocols.relay.RELAY2] site2-s2: failed starting relayer java.lang.IllegalArgumentException: JGRP000001: configuration error: the following properties in UPGRADE are not recognized: {rpcs=true}
```

**Comment by belaban** [comment]
Attribute `rpcs` is not exposed in UPGRADE 5 (it *is* in 4). Do you want me to expose it?

**Comment by pruivo** [comment]
I don't know. Is it supposed to be configurable?
I'm still fighting with other issues so I'm not sure if I want it to `true` or `false` :)

**Comment by belaban** [comment]
You're not going to need it anyway, as you don't use RPCs, just messages over a channel...

**Comment by belaban** [comment]
As `rpcs` was moved into `UpgradeBase`, and `UPGRADE` in 5 extends it, it is exposed now by default.
